// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIXsP1v8S0wsasecbIYEZvWvXpyCWoX5w',
    appId: '1:92806587925:web:ef046204c9d424d687101c',
    messagingSenderId: '92806587925',
    projectId: 'flutter-finances-a2106',
    authDomain: 'flutter-finances-a2106.firebaseapp.com',
    storageBucket: 'flutter-finances-a2106.firebasestorage.app',
    measurementId: 'G-N7FQZJPX49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiGDuYUUcYMyWiTyQmrGYnMdyKPxlLRg4',
    appId: '1:92806587925:android:4515141e41ae29a287101c',
    messagingSenderId: '92806587925',
    projectId: 'flutter-finances-a2106',
    storageBucket: 'flutter-finances-a2106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbMREb6Ha1G9E5yXkwVoqfGx2y7KnBpXE',
    appId: '1:92806587925:ios:093c785a3d67852c87101c',
    messagingSenderId: '92806587925',
    projectId: 'flutter-finances-a2106',
    storageBucket: 'flutter-finances-a2106.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbMREb6Ha1G9E5yXkwVoqfGx2y7KnBpXE',
    appId: '1:92806587925:ios:093c785a3d67852c87101c',
    messagingSenderId: '92806587925',
    projectId: 'flutter-finances-a2106',
    storageBucket: 'flutter-finances-a2106.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinances',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIXsP1v8S0wsasecbIYEZvWvXpyCWoX5w',
    appId: '1:92806587925:web:bb6255c6d88d67ae87101c',
    messagingSenderId: '92806587925',
    projectId: 'flutter-finances-a2106',
    authDomain: 'flutter-finances-a2106.firebaseapp.com',
    storageBucket: 'flutter-finances-a2106.firebasestorage.app',
    measurementId: 'G-T3WV2GQT0V',
  );
}
